name: myfirstpipeline
on: [push]

jobs:
  my-first-job:
    runs-on: agent-vinod   # ye runner machine hogi
    steps:
     - name: Run Hello World
       run: echo "Hello Agent Vinod, GitHub Actions shuru ho gaya!"
  
